version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mvsims"
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  simdjango2:
    image: mvsims
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SECRET_KEY: ${SECRET_KEY}
      AUTH_USER: ${AUTH_USER}
      AUTH_PASS: ${AUTH_PASS}
      DB_USER_NM: ${DB_USER_NM}
      DB_USER_PW: ${DB_USER_PW}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_TABLE_NAME: ${DB_TABLE_NAME}
    ports:
      - 8000:8000
    depends_on:
      - db
  apiscript:
    restart: always
    build:
      context: .
    environment:
      AUTH_USER: ${AUTH_USER}
      AUTH_PASS: ${AUTH_PASS}
      DB_USER_NM: ${DB_USER_NM}
      DB_USER_PW: ${DB_USER_PW}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_TABLE_NAME: ${DB_TABLE_NAME}
    command: ["python", "api_script.py"]
    depends_on:
      - db
